// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scwdecleebaprxtavolv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjd2RlY2xlZWJhcHJ4dGF2b2x2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwOTU4NTIsImV4cCI6MjA2NDY3MTg1Mn0.HWjh125dUQ1UKCfr-x5_zu1gJf8MqEhfqdvFvYn6Lno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);